### ISSUE TITLE
Tutorial Instruction

### ISSUE THREAD

**Issue by tomwebber4398** [tj-heat/signed-explorations#14]
Tutorial instruction for game controls e.g. WASD to move, E to interact/meow.

Meow: will bring the companion to the playable character where you can interact with them if close to an interactive object.

Acceptance Criteria: 
1. In game pop-over/modal with control instruction.
2. Press ok to continue
3. User clearly understands controls.

![Image](https://user-images.githubusercontent.com/30396497/186322395-6b9f1e6d-ff81-445e-8319-56d23d2f6da8.jpg)

- [x] Popover design created
- [x] Meow Onomatopoeia created
- [x] Window opens and closes in game
- [ ] Companion Interactive

**Comment by E-Roderick** [comment]
Closing after merging with #52
