### ISSUE TITLE
Camera Integration to Game Engine

### ISSUE THREAD

**Issue by tweeeb** [tj-heat/signed-explorations#23]
# **Description**
Implement game integration of camera and image processing model for hand sign mechanics.
 
# **Milestones**
- [x] Integration with model Completed 

Version 2
- [ ] Calibration screen
 
**Completion Deadline:** 9/09/2022

# **Dependencies**
-  Arcade library
- Calibration screen -> dependent on model dev

# **Member**
- Treffery Webb (@tweeeb)
- Ethan (@E-Roderick)

**Comment by E-Roderick** [comment]
Got OpenCV working with existing game engine ([commit](https://github.com/tj-heat/signed-explorations/commit/53551ddf41a7c4641bbdd514da1424060a62f78c)). Currently displays cam feed in a separate window.
