### ISSUE TITLE
Win Condition Version 2

### ISSUE THREAD

**Issue by tomwebber4398** [tj-heat/signed-explorations#38]
Meow -> Dog comes to players position -> Interact with dog -> Puzzle Complete -> Push Dog Through Door with Key

- [x] Meow Mechanic brings dog to player
- [x] Dog + Key push through door for win
- [x] Dog Pathfinding
- [x] Dog retrieves object items on request
- [x] Dog pathfinds to complete tasks (i.e. open door + move through door)

Dependency #15 
- [x] Dog interactable to bring up Puzzle UI

**Comment by tweeeb** [comment]
Complete
