### ISSUE TITLE
Character Dialogue Box

### ISSUE THREAD

**Issue by tomwebber4398** [tj-heat/signed-explorations#39]
- [x] Dialogue Displays empty
- [x] Click through multiple with left mouse
- [x] Pauses game but not animations

![Image](https://user-images.githubusercontent.com/30396497/191401543-9bca6dd5-7dd6-4db2-b82f-dfda82eb3e09.jpg)

Idea is this is how the dog will communicate with the user for controls etc.

**Comment by E-Roderick** [comment]
Have a screen-wide dialogue window with multiple text items working. Still need to style and add pausing feature.

**Comment by tomwebber4398** [comment]
Dialogue:

**Dialogue 1 (Before Puzzle interface is opened)**

He doesn't seem to understand what you are saying.

**Dialogue 2 (Once puzzle menu has been opened once)**
He is pointing his nose.
I think its toward the key.

**Dialogue 3 (Upon Puzzle Complete)**
He wags his tail in excitement!

**Dialogue 4 (After Puzzle complete)**
The dog patiently waits for you.

**Comment by E-Roderick** [comment]
Finished dialogue box. Haven't comprehensively tested the pausing feature but as it only blocks physics, animations should still work.

**Comment by HannahHinckfuss** [comment]
Can you make more dialogue that helps the player through the game @tomwebber4398 ?
